[build]
  command = "npm run build"
  publish = "dist"
  
# ➌ Dirige cualquier llamada a /api/submit-lead a la función serverless
[[redirects]]
  from = "/api/submit-lead"
  to   = "/.netlify/functions/submit-lead"
  status = 200
  force = true

UPSTASH_REDIS_REST_URL="https://intense-elf-10586.upstash.io"
UPSTASH_REDIS_REST_TOKEN="ASlaAAIjcDFmOGY0N2VjNmUzNTE0ZmQ2ODU5YTU5ZGE1MDVhZGViMXAxMA"
AGENT_LIST               = "juan,cristian"
